### ISSUE TITLE
Add mergebpx as dependency

### ISSUE THREAD

**Issue by alexgarbarev** [ivanzoid/mergeXcodeproj#1]
Mergepbx is available in Homebrew.
```
brew install mergepbx
```

Maybe it's worth adding as dependency if possible

**Comment by ivanzoid** [comment]
Already done: https://github.com/ivanzoid/homebrew-tap/blob/master/Formula/merge-xcodeproj.rb

**Comment by alexgarbarev** [comment]
:+1:
